name: split_it
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  firebase_core: ^1.2.0
  google_sign_in: ^5.0.4
  sign_in_with_apple: ^3.0.0
  mocktail: ^0.1.4
  shimmer: ^2.0.0
  intl: ^0.17.0
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1
  mobx_codegen: ^2.0.2
  cloud_firestore: ^2.4.0
  extended_masked_text: ^2.2.1

dev_dependencies:
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/